name: Java CI

on: [workflow_dispatch, push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cache: [maven]
        distribution: [temurin]
        java: [17, 21]
        os: [macos-latest, ubuntu-latest, windows-latest]
      fail-fast: false
      max-parallel: 4
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java ${{ matrix.java }} ${{ matrix.distribution }}
        uses: actions/setup-java@v4
        with:
          cache: ${{ matrix.cache }}
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.java }}
      - name: Run tests using install (Linux)
        run: xvfb-run -a ./mvnw install -B -V --no-transfer-progress -D"license.skip=true"
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Run tests using install (Windows/Mac)
        run: ./mvnw install -B -V --no-transfer-progress -D"license.skip=true"
        if: ${{ matrix.os != 'ubuntu-latest' }}
